version: '3'

networks:
  internal:


services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGTES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PSWD}
    ports:
      - 5432:5432
    expose:
      - 5432
    container_name: postgres_db
    networks:
      - internal

  app:
    restart: always
    build: ./app
    image: ${DOCKER_REGISTRY}/chatbot_app
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGTES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PSWD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
      - TG_TOKEN=${TG_TOKEN}
      - DOCKER_REGISTRY=${DOCKER_REGISTRY}

    depends_on:
      - db
    container_name: chatbot_app
    networks:
      - internal
